!!python/object/new:tools.attr_dict.AttrDict
dictitems:
  DATASET: !!python/object/new:tools.attr_dict.AttrDict
    dictitems:
      TEST: !!python/object/new:tools.attr_dict.AttrDict
        dictitems:
          dilate_masks: 0
          limit_seq_to: -1
          limit_to: -1
          rand_sample: -1
          subsample: 1
      TRAIN: !!python/object/new:tools.attr_dict.AttrDict
        dictitems:
          dilate_masks: 5
          limit_seq_to: -1
          limit_to: -1
          rand_sample: 30000
          subsample: 1
      VAL: !!python/object/new:tools.attr_dict.AttrDict
        dictitems:
          dilate_masks: 0
          limit_seq_to: -1
          limit_to: -1
          rand_sample: 1000
          subsample: 1
      dataset_name: pascal3d_clickp_clean_bus
      force_download: false
      sets_to_load:
      - train
      - val
      test_on_trainset: false
  MODEL: !!python/object/new:tools.attr_dict.AttrDict
    dictitems:
      APPEARANCE_LOSS: !!python/object/new:tools.attr_dict.AttrDict
        dictitems:
          border: 0.1
          huber_thr: 0.03
          n_l1_scales: 4
          sigma_coeff: 1.0
      EMBED_DB: !!python/object/new:tools.attr_dict.AttrDict
        dictitems:
          db_dim: 3
          db_size: 30000
          perc_replace: 0.01
      TRUNK: !!python/object/new:tools.attr_dict.AttrDict
        dictitems:
          architecture: hypercolumns
          depth_offset: 0.0
          dilate_start: 2
          dimout: 1
          dimout_glob: 128
          dimout_glob_alpha: 0
          encode_input_keypoints: false
          final_bias: -1.0
          final_std: 0.01
          glob_activation: true
          glob_inst_norm: false
          hc_layers:
          - 1
          - 2
          - 3
          - 4
          hcdim: 512
          kp_encoding_sig: 1.0
          n_keypoints: 12
          n_upsample: 2
          pose_confidence: true
          pretrained: true
          smooth: false
          trunk_arch: resnet50
      app_mask_image: false
      app_model_mask_gt: false
      argmin_translation_min_depth: 3.0
      argmin_translation_ray_projection: false
      c3dpo_flipped: false
      custom_basis_size: -1
      detach_app: true
      dilate_basis_loss: 0.0
      embed_db_eval: false
      huber_scaling_basis: 0.01
      huber_scaling_repro: 0.01
      log_vars:
      - objective
      - loss_basis
      - loss_alpha
      - loss_rotation
      - loss_repro
      - loss_repro_2d
      - loss_repro_ray
      - loss_vgg
      - loss_sph_emb_to_cam
      - loss_sph_sample_mask
      - loss_vgg_app
      - loss_l1_app
      - loss_ssim_app
      - sig_avg
      - pclerr_dist
      loss_weights: !!python/object/new:tools.attr_dict.AttrDict
        dictitems:
          loss_alpha: 1.0
          loss_basis: 1.0
          loss_l1_app: 1.0
          loss_repro: 0.01
          loss_repro_2d: 0.0
          loss_repro_ray: 0.0
          loss_rotation: 10.0
          loss_sph_emb_to_cam: 10.0
          loss_sph_sample_mask: 0.0
          loss_ssim_app: 0.0
          loss_vgg: 0.1
          loss_vgg_app: 0.1
      min_depth: 1.0
      n_images_for_app_model: 2
      nrsfm_exp_path: ./dataset_root/c3dpo_p3d_all
      photo_min_k: 6
      photo_reenact: false
      ray_reprojection: false
      reparametrize_nrsfm_mean: true
      repro_loss_min_ray_length: 1.0
      rot_aug_range: 0.0
      sampled_sil_n_samples: 1000
      sampled_sph_chamfer: 0
      scale_aug_range: 0.0
      spherical_embedding_radius: 0.25
      t_aug_range: 0.0
      uv_model_l2_norm: true
      uv_model_use_bn: false
  SOLVER: !!python/object/new:tools.attr_dict.AttrDict
    dictitems:
      PARAM_GROUPS: !!python/tuple []
      betas: !!python/tuple
      - 0.9
      - 0.999
      breed: sgd
      freeze_bn: false
      gamma: 0.1
      lr: 0.0003
      lr_policy: multistep
      max_epochs: 50
      milestones:
      - 40
      - 90
      momentum: 0.9
      weight_decay: 0.0005
  annotate_with_c3dpo_outputs: true
  batch_sampler: sequence
  batch_size: 10
  cfg_file: null
  collect_basis_before_eval: false
  eval_interval: 1
  exp_dir: ./exp_out/p3d-bus
  exp_idx: 1
  exp_name: test
  gpu_idx: 0
  metric_print_interval: 5
  mode: trainval
  model_zoo: ./data/torch_zoo/
  num_workers: 0
  resume: true
  resume_epoch: -1
  seed: 0
  store_checkpoints: true
  store_checkpoints_purge: 1
  store_checkpoints_purge_except_every: 25
  visdom_env: 'p3d-bus_repro_001'
  visdom_port: 8098
  visdom_server: http://100.97.69.174
  visualize_interval: 3000
